### ISSUE TITLE
Evaluate fha based failure rate on fault tree evaluation

### ISSUE THREAD

**Issue by kostobog** [kbss-cvut/fta-fmea#133]
@blcham 
- [x] - fixed by PR kbss-cvut/ava-analytics#30- ava-analytics backend should implement API to evaluate FHA based failure rate (operational failure rate based on FHA classification). The input for the services is:
  - min operational hours an
  - a set of FHA IRIs
- [x] - fixed by PR #134 - fta-fmea backend should implement 
  - call the FHA based failure rate service in ava-analytics
  - the result should be stored as  `FaultEvent.supertypes.failureRate.estimate` (estimate and failure rate if missing)  in in system specific context.
- [x] - fixed by PR kbss-cvut/fta-fmea-ui#497 - fta-fmea-ui 
  - update UI to show fha based failure rate from `FaultEvent.supertypes.failureRate.estimate`. 
  - update FHA example in TTL
- [x] - fixed by PR kbss-cvut/23ava-distribution#115 - distribution 
  - update fha example for imported sns to allow testing with operational data in  `supplier-ava\db-server\import\fta-fmea\l-39ng.t1-fha.trig` and
`supplier-ava\db-server\import\fta-fmea\l-39ng.a1-fha.trig`.
